# Generated by Django 2.2 on 2021-01-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210115_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(
                choices=[('B', 'Pagesa'), ('S', 'Transporti')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[(
                'S', 'Bluzë'), ('SW', 'Veshje Sportive'), ('OW', 'Aktivitete të jashtme')], max_length=2),
        ),
    ]
