# Generated by Django 2.2 on 2021-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210121_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('B', 'Bluza'), ('S', 'Suvenire'), ('Dh', 'Dhurata'), ('VF', 'Veshje për femra'), ('VM', 'Veshje për meshkuj')], max_length=2),
        ),
    ]
