# Generated by Django 2.2 on 2021-01-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210130_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Fanella'), ('S', 'Suvenire'), ('Dh', 'Dhurata'), ('VF', 'Veshje për femra'), ('VM', 'Veshje për meshkuj')], max_length=2),
        ),
    ]
