# Generated by Django 2.2 on 2021-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210202_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Football'), ('B', 'Basketball'), ('A', 'Auto-racing'), ('Bo', 'Boxing'), ('T', 'Të tjera')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primare'), ('S', 'sekondare')], max_length=1),
        ),
    ]
